name:

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: npm install
        run: |
          npm install
      - name: Add remote origin
        run: |
          git remote add heroku https://git.heroku.com/madels-grill-bot.git
      - name: Fetch Unshallow
        run: |
          git fetch --all --unshallow
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main -f
